var app = angular.module('myApp', ['ngRoute']);
app.config(function ($routeProvider) { 
  $routeProvider 
    .when('/home', { 
      controller: 'MainController', 
      templateUrl: 'views/home.html' 
    })  
    .when('/conhecer', {
        controller:'InApp',
        templateUrl: 'views/conhecercadeiras/app.html'
    })
    .when('/planejar', {
        controller:'InApp',
        templateUrl: 'views/planejarmatriz/app.html'
    })
    .when('/404', {
        templateUrl: 'views/404.html'
    })
    .otherwise({ 
      redirectTo: '/home' 
    }); 
});

app.factory('userService', function($http){
    var service = {   
        selectedObject: {
        id:99999999,
        name:'Nome da Cadeira',
         color:'#6A96DD',
         tipo: 'Tipo da cadeira',
         chp: 0,
         cht: 0,
         professor: '-------',
         ementa: 'Ementa',
         pre:'------',
         comentarios: [
         {
            avatar:'https://68.media.tumblr.com/avatar_16b98ea93eb7_128.png',
            nick:'Nick',
            numero:'2',
            coment:'Talvez o tempo te ponha na sua escola pois não terás melhor professor que ele.'
         }
         ]
        },
        trilhas: [
                    {
                        matriz:[        [ '0', '1', '2', '3', '4', ''],
                                        [ '5', '6', '7', '8', '9', ''],
                                        ['10','11','12','13','14', ''],
                                        ['15','22','26','27',  '', ''],
                                        ['28','30','31','54','61', ''],
                                        ['16','17','45','63','69', ''],
                                        ['18','19','47','80',  '', ''],
                                        ['20','21',  '',  '',  '', '']
                                                                     ],
                        nome: 'Audiovisual',
                        fixa: true
                },  
        ],
        matriz: [
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','','']
        ],
        matriz_salva: [
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','','']
        ], 
        matriz_vazia: [
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','',''],
        ['','','','','','']
        ], 
        limpo: true,
        semestre: [
                    [ '0', '1', '2', '3', '4', ''],
                    [ '5', '6', '7', '8', '9', ''],
                    ['10','11','12','13','14', ''],
                    ['15','','','',  '', ''],
                    ['','','','','', ''],
                    ['16','17','','','', ''],
                    ['18','19','','',  '', ''],
                    ['20','21',  '',  '',  '', '']
        ],

        filterBy: [],        
        perfil: { 
            avatar: 'https://pbs.twimg.com/profile_images/658761489017344000/n3wFCZov_reasonably_small.jpg',
            nick: 'Estudante que não gosta de problematizar'
        },
        cadeiras: [
    {
        id:0,
        name:'Autoração Multimídia I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 16:00-18:00',
         professor1: 'Arthur de Oliveira',
         horario2: 'TER/QUI 14:00-16:00',
         professor2: 'Arthur de Oliveira',
         ementa:'Imagem estática bitmap: seleção, recorte, tratamento, colorização e filtragem. Imagem estática vetorial: primitivas gráficas e suas propriedades, introdução à ilustração digital e técnica de vetorização. Imagem animada: animação quadro a quadro, animação por interpolação de posição, rotação, escala e forma. Imagem interativa: componentes interativos e programação de resposta a eventos.',
         pre:'Nenhum',
         apar: true,
         semestre:1,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:1,
        name:'Desenho I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'QUA/SEX 16:00-18:00',
         professor1: 'Liandro Roger',
         horario2: 'QUA/SEX 14:00-16:00',
         professor2: 'Liandro Roger',
         ementa:'Técnicas e uso dos instrumentos de desenho. Desenho a mão livre e expressão gráfica. Técnica de composição. Proporção, luz, sombra, textura, fundo e figura. Noções básicas de desenho auxiliado por computador.',
         pre:'Nenhum',
         apar: true,
         semestre:1,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:2,
        name:'História do Design',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'QUA/SEX 14:00-16:00',
         professor1: '',
         horario2: 'QUA/SEX 16:00-18:00',
         professor2: '',
         ementa:'Conceitos de design. Transformações sócio-culturais na história do design. Principais movimentos, designers e artefatos da história do design. O design no Brasil. Design, arte e cultura material.',
         pre:'Nenhum',
         apar: true,
         semestre:1,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:3,
        name:'Introdução a Sistemas e Mídias Digitais',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Levi Bayde',
         horario2: '',
         professor2: '',
         ementa:'Introdução à mídia digital. Fundamentos da comunicação e mídias digitais. Convergência de mídias. Entretenimento digital e jogos eletrônicos. Cadeia produtiva de mídia digital interativa: etapas, processos, técnicas, profissionais, equipes e produtos. Aspectos psicológicos e comportamento do usuário em produtos multimídia.',
         pre:'Nenhum',
         apar: true,       
         semestre:1,   
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:4,
        name:'Programação I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'TER 14:00-16:00 QUI 14:00-16:00',
         professor1: 'EMANUEL FERREIRA COUTINHO , MARA FRANKLIN BONATES',
         horario2: 'TER 16:00-18:00 QUI 16:00-18:00',
         professor2: 'MARA FRANKLIN BONATES , EMANUEL FERREIRA COUTINHO',         
         professor: '',
         ementa:'Conceitos de linguagens de programação. Introdução aos paradigmas de programação. Orientação a Objetos: Classe, Objeto, Atributos, Eventos/Métodos e encapsulamento. Problemas formais e resolução de problemas. Utilização de uma linguagem em pseudocódigo ou visual (Visual Programming Language - VPL). Conceitos e estruturas básicas de Algoritmos. Programação de algoritmos. Estruturas condicionais e de repetições. Variáveis compostas homogêneas unidimensionais (Vetores). Prática direcionada.',
         pre:'Nenhum',
         apar: true,     
         semestre:1,     
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:5,
        name:'Cognição e Tecnologias Digitais',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'SEG 18:00-22:00',
         professor1: 'Raquel Santiago, José Aires de Castro',
         horario2: '',
         professor2: '',
         ementa:'Principais teorias do desenvolvimento cognitivo e suas aplicações na criação de design WEB e Interfaces Digitais. Desenvolvimento cognitivo na cibercultura. Tecnologias digitais e teorias recentes sobre Cognição: cognição situada e cognição distribuída. Contribuições da linguística na compreensão de gêneros textuais emergentes.',
         pre:'Nenhum',
         apar: true,      
         semestre:2,    
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:6,
        name:'Matemática Aplicada a Multimídia I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Introdução: sistemas, mídias e matemática. Funções. Geometria Euclidiana: conceitos e exemplos práticos. Coordenadas polares. Lugares geométricos: definições, equações e aplicações. Conjuntos. Cardinalidade. Diagramas de Venn e de Euler. Operações com conjuntos. Relações entre conjuntos. Combinatória. Fenômenos aleatórios, frequência, e exemplos práticos. População, amostra, e amostragem. Média, mediana e moda: definição, significado e aplicações. Amplitude, variância e desvios. Distribuição normal e distribuição de Poisson.',
         pre:'Nenhum', 
         apar: true,
         semestre:2,    
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:7,
        name:'Comunicação Visual I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Paula Marques',
         horario2: 'TER/QUI 20:00-22:00',
         professor2: 'Paula Marques',
         ementa:'Conceitos e elementos da Comunicação Visual: elementos e propriedades gráficas e níveis da linguagem visual. Teoria da Gestalt aplicada à comunicação visual. Técnicas básicas de composição visual e layout. Princípios de design gráfico. Tipografia e harmonias cromáticas. Definição de identidade visual.',
         pre:'Nenhum',
         apar: true,  
         semestre:2,    
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:8,
        name:'Programação II',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 10:00-12:00',
         professor1: 'Ricardo Brauner',
         horario2: '',
         professor2: '',
         ementa:'Variáveis, operadores, escopo e bloco de comandos, vetores, matrizes, strings funções e orientação a objetos.',
         pre:'Programação I',
         pre1: 4,
         apar: true,    
         semestre:2,          
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:9,
        name:'Narrativas Multimídia',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Bases da narrativa a partir de elementos da análise do discurso. Roteiro e suas características a partir da mídia utilizada. Documentação e suas ferramentas: storyboard, storyreel, timeline, interação entre as mídias. Navegabilidade. Arquitetura da informação e suas fases: esquema de organização, modelo de narrativa e sistema de rotulação.',
         pre:'Nenhum', 
         apar: true, 
         semestre:2,    
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {   
        id: 10,
        name:'Design de Interfaces Gráficas',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 14:00-16:00',
         professor1: '',
         horario2: 'TER/QUI 16:00-18:00',
         professor2: '',
         ementa: 'Introdução às interfaces gráficas. Design gráfico aplicado às interfaces gráficas. Tecnologias de interfaces gráficas. Interfaces gráficas em sistemas multimídia online e offline. Interfaces gráficas em sistemas embarcados. Interfaces gráficas para jogos digitais. Avaliação e testes. Estudos de Caso ',
         pre:'Comunicação Visual I',
         pre1: 7,
         matriz: true, 
         existe: true,
         semestre:3,
         apar: true,
         comentarios: [
         {
            avatar:'https://68.media.tumblr.com/avatar_bf63549f5238_128.png',
            nick:'Estudante esforçado',
            numero:'4',
            coment:'Educação é o que resta depois de ter esquecido tudo que se aprendeu na escola.'
         }
         ]
        },

    {
        id:11,
        name:'Interação Humano-Computador',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 16:00-18:00',
         professor1: 'Maria de Fátima',
         horario2: 'TER/QUI 14:00-16:00',
         professor2: 'Cátia Luzia',
         ementa:'Introdução à interação humano-computador. Fatores de Qualidade de Uso. Fatores humanos em interação humano-computador. Análises e reflexões sobre design industrial e ergonomia. Análise de interfaces gráficas. Design Centrado no Usuário. Design de interação. Avaliação e testes. Estudos de caso.',
         pre: 'Nenhum',
          apar: true,
          semestre:3,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:12,
        name:'Introdução à Cibercultura',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'QUA/SEX 14:00-16:00',
         professor1: 'Eduardo Junqueira',
         horario2: 'QUA/SEX 16:00-18:00',
         professor2: 'Eduardo Junqueira',
         ementa: 'Princípios teóricos da cibercultura, Inclusão digital e social, Ciberativismo e Cultura Livre, Redes Sociais Virtuais, Liberdade e Privacidade na internet.',
         pre:'Nenhum',
         apar: true,
         semestre:3,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:13,
        name:'Autoração Multimídia II',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'QUA/SEX 16:00-18:00',
         professor1: 'Paula Marques, Arthur de Oliveira',
         horario2: 'QUA/SEX 14:00-16:00',
         professor2: 'Paula Marques, Arthur de Oliveira',
         ementa:'Técnicas de animação digital: princípios e técnicas básicos, geração de clips de filme e sonorização. Técnicas de interatividade digital: geração e programação de elementos interativos. Publicação/disponibilização de aplicação final. Integração de mídia externa, geração de bibliotecas e uso de componentes. Desenvolvimento de projeto final.',
         pre:'Autoração Multimídia I',
         pre1: 0,
         apar: true,
         semestre:3,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:14,
        name:'Projeto Integrado I',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Paula Marques, Catia Luzia, Maria de Fatima',
         horario2: '',
         professor2: '',
         ementa:'Definição de características iniciais do produto multimídia de complexidade baixa. Estabelecimento de metodologia de desenvolvimento. Geração de produto, de acordo com a metodologia previamente adotada. Apresentação e discussão de resultados intermediários e finais.',
         pre:'Comunicação Visual I, Programação I',
         pre1: 4,
         pre2: 7,
         apar: true,
         semestre:3,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:15,
        name:'Metodologia de Pesquisa Científica',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'QUA 18:00-22:00',
         professor1: 'Raquel Santiago, Fernando Lincoln',
         horario2: 'SEG/QUA 14:00-16:00',
         professor2: 'Luciana de Lima',
         ementa:'Fundamentos de metodologia científica. Noções de processo de elaboração de projetos. Elementos do projeto: motivação, justificativa, problema, referencial teórico, objetivo, metodologia, referências bibliográficas. Modalidades de TCC. Normas de trabalho científico. Elaboração e apresentação de projetos em multimídia.',
         pre:'Projeto Integrado I',
         pre1: 14,
         apar: true,
         semestre:4,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:16,
        name:'Ética e Política Autoral',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'SEX 18:00-22:00',
         professor1: 'Fernando Lincoln',
         horario2: '',
         professor2: '',
         ementa:'Ética, Moral e Liberdade – relações e conceitos. A Ética na História. A Ética e a Moral nos campos social e profissional. A Propriedade Intelectual. Códigos de Ética Profissional. Ética hacker. Novas Tecnologias associadas ao Direito Autoral. Legislação vigente relacionada ao Direito Autoral. Mídia, direitos humanos e cidadania.',
         pre:'Nenhum',  
         apar: true,
         semestre:6,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:17,
        name:'Gestão de Projetos Multimídia',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'SEG/QUA 18:00-20:00',
         professor1: 'Edgar Marçal',
         horario2: '',
         professor2: '',
         ementa:'Introdução a Gestão de Projetos. Características dos Projetos Multimídia. Modelos de Projetos Multimídia. Os Profissionais envolvidos em Projetos Multimídia. Ciclo de Vida de Projetos Multimídia. Gerenciamento da Equipe. Gerenciamento do Cronograma. Gerenciamento dos Riscos. Gerenciamento da Qualidade. Plano de Comunicação. Implantação e Pesquisa de Opinião com o Cliente. Ferramentas de Acompanhamento. Economia Criativa. Elaboração de Plano de Negócio.',
         pre:'Projeto Integrado I',
         pre: 14,
         apar: true,
         semestre:6,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:18,
        name:'Projeto de Trabalho Final',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 14:00-16:00',
         professor1: 'Raquel Santiago, Fernando Lincoln',
         horario2: '',
         professor2: '',
         ementa:'Processo de elaboração de projetos. Roteiro: título, caracterização do problema e justificativa, objetivos, metas, metodologia, cronograma e referências bibliográficas. Formulação, apresentação e defesa de projeto.',
         pre:'Nenhum',  
         apar: true,
         semestre:7,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:19,
        name:'Projeto Integrado II',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         horario1: 'SEX 14:00-18:00',
         professor1: 'Ernesto Trajano, Windson Viana, Andrea Pinheiro',
         horario2: '',
         professor2: '',
         ementa:'Definição de características iniciais do produto multimídia de complexidade baixa. Estabelecimento de metodologia de desenvolvimento. Geração de produto, de acordo com a metodologia previamente adotada. Apresentação e discussão de resultados intermediários e finais.',
         pre:'Metodologia da Pesquisa Científica',
         pre1: 15,
         apar: true, 
         semestre:7,         
         matriz: true, 
         existe: true, 
         comentarios: []
        },

    {
        id:20,
        name:'Trabalho de Conclusão do Curso II',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'Processo de elaboração de projetos. Roteiro: título, caracterização do problema e justificativa, objetivos, metas, metodologia, cronograma e referências bibliográficas. Formulação, apresentação e defesa de projeto.',
         pre:'Trabalho de Conclusão do Curso I',
         pre1: 18,
         apar: true,
         semestre:8,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:21,
        name:'Seminários em Multimídia',
         color:'#6A96DD',
         tipo: 'Obrigatória',
         chp: 0,
         cht: 4,
         horario1: 'SEG/SEX 18:00-20:00',
         professor1: 'Henrique Barbosa',
         horario2: '',
         professor2: '',
         ementa:'Eventos com convidados apresentando tendências nas áreas relacionadas a Sistemas e Mídias Digitais. Leitura e análise de artigos de congressos e publicações relacionadas com Sistemas e Mídias Digitais. Discussões dos assuntos abordados',
         pre:'Nenhum',  
         apar: true,
         semestre:8,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:22,
        name:'Análise e Projeto de Sistemas',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Edgar Marçal',
         horario2: 'TER/QUI 16:00-18:00',
         professor2: 'Levi Bayde',
         ementa:'Introdução à análise de sistemas. Ciclo de vida e os paradigmas de desenvolvimento de software. Abordagens de desenvolvimento e projeto de sistemas. Metodologias de modelagem de sistemas. UML - Unified Modeling Language. Especificação e documentação em UML com Ferramentas CASE. Desenvolvimento de projetos de sistemas em UML. Mapeamento Objeto-Relacional. Uso de um Processo de Desenvolvimento voltado para Sistemas Multimídia.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:4,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:23,
        name:'Estruturas de Dados',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'SEG/SEX 18:00-20:00',
         professor1: 'Gabriel Antoine, Leonardo Oliveira',
         horario2: '',
         professor2: '',
         ementa:'Programação C. Listas: estática, dinâmica, simplesmente encadeada, duplamente encadeada, circular etc. Fila em Estrutura Dinâmica e estática. Pilha em estrutura dinâmica e estática. Árvores binárias e balanceadas. Algoritmos de ordenação e de busca. Complexidade. Recursividade.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:4,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:24,
        name:'Redes de Computadores',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 20:00-22:00',
         professor1: 'Windson Viana',
         horario2: '',
         professor2: '',
         ementa:'Introdução às redes de computadores e a Internet. Estudo aprofundado das camadas TCP/IP: Aplicação, Transporte, Rede, Enlace e Física. Teoria e Prática com os protocolos da camada aplicação mais utilizados: (HTTP. SMTP, FTP, VoiP, DNS, etc.). Controle de Congestionamento e Fluxo em TCP. Topologia, Endereçamento e Roteamento em redes TCP/IP. Redes P2P. Programação em Sockets TCP e UDP.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:4,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:25,
        name:'Desenho II',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Liandro Roger',
         horario2: '',
         professor2: '' ,
         ementa:'Linguagem e criação visual. Técnicas de representação e elementos gráficos. Técnicas de desenho manual e digital. Análise e experimentação gráfica. Representação visual aplicada',
         pre:'Desenho I',
         pre1: 1,
         apar: true,
         semestre:4,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:26,
        name:'Fotografia',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'SEG/SEX 20:00-22:00',
         professor1: 'Ismael Pordeus',
         horario2: '',
         professor2: '',
         ementa:'Compreender os conceitos de imagem e fotografia, conhecendo e explorando as potencialidades artísticas e documentais da captura de imagens digitais, a partir do domínio técnico da câmera digital e do conhecimento dos gêneros, práticas e expermentos na produção contemporânea das imagens.',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:4,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:27,
        name:'Semiótica Aplicada',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 0,
         cht: 4,
         horario1: 'SEG/QUA 18:00-20:00',
         professor1: 'Georgia da Cruz',
         horario2: '',
         professor2: '',
         ementa:'Perspectiva histórica e contemporânea da semiótica e sua relação com as mídias digitais, com particular ênfase às teorias semióticas e à semiótica da cultura e da arte. Conceitos de signo e significação. Principais elementos de semiótica aplicada.Elementos da retórica na arte e na mídia.',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:4,
         matriz: true, 
existe: true,
         comentarios: []
        },
    {
        id:28,
        name:'Engenharia de Software',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 0,
         cht: 4,
         horario1: 'QUA/SEX 14:00-16:00',
         professor1: 'Maria de Fatima',
         horario2: '',
         professor2: '',
         ementa:'Evolução, terminologia e estado da arte da Engenharia de Software. Modelos de processo de desenvolvimento. Fases do processo de desenvolvimento. Principais modelos, metodologias, técnicas e ferramentas utilizadas na Engenharia de Software.Qualidade do produto e processo. Padrões de desenvolvimento.',
         pre:'Análise e Projeto de Sistemas',
         pre1: 22,
         apar: true,
         semestre:5,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:29,
        name:'Banco de Dados I',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 16:00-18:00',
         professor1: 'Leonardo Oliveira',
         horario2: '',
         professor2: '',
         ementa:'Sistemas de Banco de Dados. Modelo Entidade-Relacionamento. Modelo Relacional. Projeto de banco de dados. Linguagem SQL. Aplicações em Bancos de Dados. Restrições de integridade em banco de dados relacional.',
         pre:'Estrutura de Dados',
         pre1: 23,
         apar: true,
         semestre:5,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:30,
        name:'Comunicação Visual II',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 4,
         cht: 0,
         horario1: 'QUA/SEX 16:00-18:00',
         professor1: 'Andrei Bosco Bezerra Torres',
         horario2: '',
         professor2: '',
         ementa:'Materiais. Construção do significado. Gestalt aplicada à programação visual. Uso da cor e harmonias cromáticas. Criatividade. Sistemas de identidade visual. A comunicação visual aplicada a sistemas digitais.',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:5,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:31,
        name:'Design de Som',
         color:'#0FC488',
         tipo: 'Eletiva',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 14:00-16:00',
         professor1: 'Ernesto Trajano',
         horario2: '',
         professor2: '',
         ementa:'O universo sonoro e a estética do som. Fundamentos de composição musical. Estilos musicais e suas perspectivas midiáticas. Uso narrativo da trilha sonora e de efeitos sonoros em projetos multimídia. Técnicas de captura, tratamento e edição de som. Experimentos em sonorização.',
         pre:'Narrativas Multimídias',
         pre1: 9,
         apar: true,
         semestre:5,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:32,
        name:'Banco de Dados Aplicado à Multimídia',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Sistemas de Banco de Dados. Modelo Entidade-Relacionamento. Modelo Relacional. Projeto de banco de dados. Linguagem SQL. Aplicações em Bancos de Dados. Restrições de integridade em banco de dados relacional.',
         pre:'Banco de Dados I',
         pre1: 29, 
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:33,
        name:'Cibercultura E Educação: Novas Práticas',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'QUI 14:00-18:00',
         professor1: 'Robson Carlos Loureiro, Luciana de Lima',
         horario2: '',
         professor2: '',
         ementa:'Desenvolvimento de projetos aplicados incorporando novas formas de ensinar e de aprender e novas tecnologias digitais em rede. Paradigmas teóricos da cibercultura e da interdisciplinaridade. Práticas educativas na cibercultura e com as novas tecnologias em rede. Novas metodologias de docência e aprendizagem.',
         pre:'Nenhum',
         apar: true,  
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:34,
        name:'Computação Física',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 20:00-22:00',
         professor1: 'Clemilson Costa dos Santos',
         horario2: '',
         professor2: '',
         ementa:'Introdução a Interação Humano-Computador. Fatores Humanos em Interação Humano-Computador. Análise e reflexão sobre Design. Métodos e técnicas utilizadas em Interação Humano-Computador. Projeto Prático.',
         pre:'Programação I',
         pre1: 4,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true,
         comentarios: []
        },
    {
        id:35,
        name:'Computação Gráfica',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Introdução, Sistemas Gráficos, Primitivas Gráficas, Rasterização e Algoritmos de Bresenham, Representação e Modelagem de Objetos, Cor e sistemas de cores, OpenGL, Transformações Geométricas 2D e 3D, Projeções Paralelas e Perspectivas, Matrizes de Visualização e de Projeção, Z-Buffer e buffers de vídeo, Texturização e Listas de Exibição, Iluminação, Projetos em Computação Gráfica.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:36,
        name:'Comunicação em Novas Mídias',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         professor: '',
         ementa:'',
         pre:'Narrativas Multimídias',
         pre1: 9,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:37,
        name:'Concepção de Cenários e Personagens',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 20:00-22:00',
         professor1: 'Liandro Roger',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Ferramentas de Modelagem Tridimensional I',
         pre1: 49,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:38,
        name:'Cultura de Jogos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         horario1: 'TER/QUI 10:00-12:00',
         professor1: 'Wellington Wagner',
         horario2: '',
         professor2: '',
         ementa:'Definição e conceituação de jogos eletrônicos. Narratologia e Ludologia. História dos Jogos eletrônicos. Plataformas e dispositivos. Influências dos jogos na cultura contemporânea. Tipologia dos jogos eletrônicos. Avaliação e Crítica de Games.',
         pre:'Nenhum',
         apar: true,  
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:39,
        name:'Desenvolvimento de Aplicações Distribuídas',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Sistemas Distribuídos',
         pre1: 75,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:40,
        name:'Desenvolvimento de Jogos Casuais',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'Apresentação da ideia de jogos casuais e respectivos conceitos envolvidos (diversão, jogabilidade, imersão, simplicidade de uso, etc.). Discussão e prática de técnicas e tecnologias voltadas ao desenvolvimento de jogos casuais. Especificação de jogo casual. Desenvolvimento de jogo casual. Aplicação de jogo casual. Avaliação de jogo casual.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:41,
        name:'Desenvolvimento de Motores Gráficos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'SEG/QUA 16:00-18:00',
         professor1: 'José Gilvan',
         horario2: '',
         professor2: '',
         ementa:'Conceitos fundamentais. Pipelines gráficas. Pipelines gráficas programáveis. Câmeras. Malhas. Materiais. Animação. Representação de cenas. Estruturas de dados e algoritmos para aceleração gráfica. Técnicas básicas de renderização de efeitos especiais. Construção de uma API de alto nível. Aspectos de integração com outros componentes. Estudos de casos.',
         pre:'Computação Gráfica, Programação para Jogos II',
         pre1: 35,
         pre2: 71,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:42,
        name:'Design de Jogos Digitais',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'',
         pre:'Narrativas Multimídia',
         pre1: 9,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:43,
        name:'Design Instrucional',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Nenhum',
         apar: true,
         semestre:9,
         matriz: true, 
existe: true,
         comentarios: []
        },
    {
        id:44,
        name:'Direção de Arte para Multimídia',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Autoração Multimídia I',
         pre1: 0,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:45,
        name:'Edição Audiovisual',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 20:00-22:00',
         professor1: 'Ismael Pordeus, Neil Armstrong',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Linguagem Audiovisual',
         pre1: 63,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:46,
        name:'Educomunicação',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'QUA 18:00-22:00',
         professor1: 'Andrea Pinheiro, Catia Luzia',
         horario2: '',
         professor2: '',
         ementa:'Fundamentos epistemológicos da inter-relação entre comunicação e educação. Aspectos históricos da educomunicação. Mídia e educação. As contribuições ibero-americana, europeia e norte-americana. A teoria das mediações. Educomunicação, movimentos sociais e terceiro setor. O perfil do profissional educomunicador. Pesquisa acadêmica em educomunicação. Políticas públicas na área de educomunicação.',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:47,
        name:'Experimentos em Multimídia I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'QUA 08:00-12:00',
         professor1: 'Daniely Ildegardes, Glaudiney Moreira',
         horario2: '',
         professor2: '',
         ementa:'Apresentação, análise e discussão de tendências na área de multimídia. Avaliação de soluções técnicas e tecnológicas que viabilizem a construção de produtos/artefatos de mídia digital de diversos gêneros (aplicativos, serviços online, jogos eletrônicos, instalações multimídia interativas, etc). Construção de protótipos, realização de testes, avaliação de resultados, desenvolvimento de modelos finais e exposição/aplicação junto à comunidade.',
         pre:'Autoração Multimídia I, Programação I.',
         pre1: 0,
         pre2: 4,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:48,
        name:'Experimentos em Tipografia Digital',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Tipografia: história e evolução. Nomenclatura e classificação dos tipos. A tipografia como meio de expressão. Aplicação em projetos gráficos.',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:49,
        name:'Ferramentas de Modelagem Tridimensional I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'SEG/SEX 18:00-20:00',
         professor1: 'Mara Franklin, Andrei Bosco',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:50,
        name:'Filosofia da Tecnologia',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         horario1: 'SEG/SAB 20:00-22:00',
         professor1: 'Robson Carlos',
         horario2: '',
         professor2: '',
         ementa:'Filosofia da ciência e da tecnologia, o que é tecnologia? Racionalidade tecnológica, determinismo tecnológico, mulheres feminismo e tecnologia e antitecnologia.',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:51,
        name:'Frameworks de Software',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'Definir frameworks de software. Estudar frameworks de persistência de dados, log de operações, gráficos, geração de relatórios. Estudar tópicos avançados ou atuais em frameworks de software.',
         pre:'Engenharia de Software',
         pre1: 28,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:52,
        name:'Gerência de Projetos de Software',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         professor: '',
         ementa:'',
         pre:'Nenhum', 
         apar: true, 
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:53,
        name:'Gestão de Negócios em Multimídia',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         professor: '',
         ementa:'',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:54,
        name:'Instalações Multimídia',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Clemilson Costa',
         horario2: '',
         professor2: '',
         ementa:'Apresentação, análise e discussão do conceito de instalação multimídia. Avaliação de soluções técnicas e tecnológicas que viabilizem a construção de instalações multimídia interativas de diversos gêneros. Construção de protótipos, realização de testes, avaliação de resultados, desenvolvimento de modelos finais e exposição/aplicação junto à comunidade.',
         pre:'Matemática Aplicada a Multimídia, Comunicação Visual I',
         pre1: 6,
         pre2: 7,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:55,
        name:'Inteligência Computacional Aplicada a Jogos I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:56,
        name:'Inteligência Computacional Aplicada a Jogos II',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Tópicos avançados em inteligência computacional para jogos. Sistemas multiagentes, aprendizado de máquina, redes neurais, motores para jogos e projetos de inteligência computacional para jogos.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true,
         comentarios: []
        },
    {
        id:57,
        name:'Introdução a Computação Móvel e Ubíqua',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Computação Ubíqua – Conceitos e Tecnologias, Histórico. Principais Características. Cenários. Aplicações. Desafios. Tecnologias de comunicação sem fio. Sensibilidade ao Contexto. Adaptabilidade e Adaptatividade. Personalização, Customização. Adaptação Estática e Adaptação Dinâmica. Sensores. Desenvolvimento de software móvel. Fragmentação e seus desafios. Técnicas de programação para dispositivos móveis. Plataformas. Explorando novos recursos.',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:58,
        name:'Jogos Distribuídos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 16:00-18:00',
         professor1: 'Jose Gilvan',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Sistemas Distribuídos',
         pre1: 75,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:59,
        name:'Jogos Multiplataforma',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'',
         pre:'Programação para Jogos I',
         pre1: 70,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:60,
        name:'Jogos para Consoles',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Introdução e histórico. Arquiteturas modernas de microprocessadores. Análise das cargas de trabalho nos jogos. Gargalos computacionais. Arquiteturas de console. Hardware gráfico. Processo de desenvolvimento: técnicas de programação e ferramentas. Distribuição de jogos. Estudo de caso.',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:61,
        name:'Laboratório de Criatividade',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 10:00-12:00',
         professor1: 'Georgia da Cruz',
         horario2: '',
         professor2: '',
         ementa:'Definições de criação, inovação e criatividade. Os processos criativos e seu uso no Design. Desenvolvimento e a aplicação prática de técnicas criativas. Bloqueios e Desbloqueadores. Técnicas de geração de ideias.',
         pre:'Comunicação Visual I',
         pre1: 7,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:62,
        name:'Laboratório de Programação',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:63,
        name:'Linguagem Audiovisual',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Georgia da Cruz',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Narrativas Multimídias',
         pre1: 9,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:64,
        name:'Linguagem de Programação Script',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Wellington Wagner, Ricardo Brauner',
         horario2: '',
         professor2: '',
         ementa:'Introdução a linguagem script. Linguagem compilada X interpretada. Prototipagem. Programação Web. Scripts para configuração e extensão de softwares. Programação em uma linguagem de programação script.',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:65,
        name:'Matemática e Física para Jogos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'SEG/QUA 14:00-16:00',
         professor1: 'Jose Gilvan',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:66,
        name:'Mitologia Universais',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         horario1: 'SEG/QUA 10:00-12:00',
         professor1: 'Levi Bayde',
         horario2: '',
         professor2: '',
         ementa:'Mitologia, simbolismo e características das civilizações grega, egípcia e nórdica. Outras mitologias e civilizações menos conhecidas. Comparação entre essas civilizações e mitologias, e semelhança de seus simbolismos. Geração de civilizações fictícias a partir do entendimento das bases reais.',
         pre:'Nenhum', 
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:67,
        name:'Mitos e Arquétipos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         horario1: 'TER/QUI 10:00-12:00',
         professor1: 'Levi Bayde, Glaudiney Moreira',
         horario2: '',
         professor2: '',
         ementa:'O que é mito. O que são arquétipos. Tipos de arquétipos. Origens dos mitos. Jornada do herói. Mitos de Criação. Mitos de Metamorfoses. Criaturas. Universos Fictícios. Heróis, heroínas e anti-heróis. Mitos modernos.',
         pre:'Nenhum',  
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:68,
        name:'Procecessamento de Áudio',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 0,
         cht: 4,
         professor: '',
         ementa:'Introdução, aspectos históricos, princípios matemáticos e som perceptual.Representação digital de áudio, Teorema de Nyquist, qualidade de áudio, codificação e streaming. Processamento, mixagem, filtragem, controle de frequência, remoção de ruído e restauração. Síntese de som: instrumentos virtuais, saída digital de áudio, som tridimensional, sincronização e projeto de sistema básico de áudio.',
         pre:'Programação I',
         pre1: 4,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:69,
        name:'Produção Audiovisual',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Ismael Pordeus',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Edição Audiovisual',
         pre1: 45,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:70,
        name:'Programação para Jogos I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:71,
        name:'Programação para Jogos II',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Programação para Jogos I',
         pre1: 70,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:72,
        name:'Programação para Web I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'TER/QUI 10:00-12:00',
         professor1: 'Leonardo Oliveira, Emanuel Ferreira',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Programação II',
         pre1: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:73,
        name:'Programação para Web II',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         horario1: 'SEG/QUA 20:00-22:00',
         professor1: 'Leonardo Oliveira',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Programação para Web I',
         pre1: 72,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:74,
        name:'Redação para Mídias Digitais',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'SEG 14:00-18:00',
         professor1: 'Andrea Pinheiro',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Narrativas Multimídias, Semiótica Aplicada',
         pre1: 9,
         pre2: 27,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:75,
        name:'Sistemas Distribuídos',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'QUA/SEX 10:00-12:00',
         professor1: 'Windson Viana',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Redes de Computadores, Programação II',
         pre1: 24,
         pre2: 8,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:76,
        name:'Sistemas Embarcados',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Clemilson Costa',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'Análise e Projeto de Sistemas',
         pre1: 22,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:77,
        name:'Técnicas de Animação Analógica',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Desenho I',
         pre1: 1,
         apar: true,
         semestre:9,
         matriz: true, 
existe: true, 
         comentarios: []
        },
    {
        id:78,
        name:'Técnicas de Animação Digital I',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Técnicas de Animação Analógica',
         pre1: 77,  
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:79,
        name:'Teste de Software Aplicado',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 2,
         cht: 2,
         professor: '',
         ementa:'Introdução a Testes de Software. Conceitos e Tipos de Testes de Software. Processos de Testes de Software. Testes Unitários. TDD.',
         pre:'Programação I',
         pre1: 4,
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:80,
        name:'Videografismo',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: 4,
         cht: 0,
         professor: '',
         ementa:'',
         pre:'Edição Audiovisual, Ferramentas de Modelagem Tridimensional I',
         pre1: 45,
         pre2: 49,
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:81,
        name:'Análise de Desempenho',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: '-',
         cht: '-',
         horario1: 'SEG 14:00-18:00',
         professor1: 'Emanuel Ferreira',
         horario2: '',
         professor2: '',
         ementa:'Introdução a análise de desempenho. Projeto de experimentos. Métricas, fatores e níveis. Medições. Estatística básica. Simulação e emulação de comportamento. Aplicação de projeto de experimentos. Análise de desempenho de experimentos.',
         pre:'',
         pre1: '',
         pre2:'' ,
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:82,
        name:'Interação Humano Computador II',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: '-',
         cht: '-',
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Catia Luzia',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'',
         pre1: '',
         pre2:'' ,
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:83,
        name:'Produção Audiovisual para Crianças e Adolescentes',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: '-',
         cht: '-',
         horario1: 'QUA 14:00-18:00',
         professor1: 'Andrea Pinheiro',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'',
         pre1: '',
         pre2: '',
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:84,
        name:'Programação para Dispositivos Móveis',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: '-',
         cht: '-',
         horario1: 'TER/QUI 18:00-20:00',
         professor1: 'Windson Viana',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'',
         pre1:'' ,
         pre2: '',
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
    {
        id:85,
        name:'Teoria e Crítica do Design',
         color:'#AC84E0',
         tipo: 'Optativa',
         chp: '-',
         cht: '-',
         horario1: 'TER/QUI 16:00-28:00',
         professor1: 'Ticiane de Gois',
         horario2: '',
         professor2: '',
         ementa:'',
         pre:'',
         pre1:'' ,
         pre2:'' ,
         apar: true,
         semestre:9,
         matriz: true, 
         existe: true, 
         comentarios: []
        },
        ]
    }
    return service;
});
